name: windows

on: [push, pull_request]

jobs:

  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version:
          - 'windows-2019'
          - 'windows-latest'
    env:
      CXXFLAGS: /MP
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            
      - name: Sync repository
        uses: actions/checkout@v2
        
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2!
        with:
          path: '${{ github.workspace }}/qt_installation/'
          key: ${{ runner.os }}-QtCache
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: '5.15.2'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt_installation/'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build Plotjuggler
        shell: pwsh
        run: >
          cmake -Ax64 -T host=x64 -B build -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=RelWithDebInfo PlotJuggler;
          cmake --build build --config RelWithDebInfo --target install
          
      - uses: actions/upload-artifact@v1
        with:
          name: install-${{ matrix.windows-version }}
          path: install
